// js/config.mjs

// Firmware: PS4 12.02
// OFFSETS VALIDADOS/REFINADOS COM BASE NA ANÁLISE DE DISASSEMBLY (ArrayBuffer.txt, JSON.txt, m_type...)
export const JSC_OFFSETS = {
    JSCell: {
        STRUCTURE_ID_OFFSET: 0x00,
        FLAGS_OFFSET: 0x04,
        STRUCTURE_POINTER_OFFSET: 0x8,
    },
    Structure: { /* ... (placeholders, validar) ... */ },
    JSObject: {
        BUTTERFLY_OFFSET: 0x08, // Ou 0x10, VALIDAR
    },
    ArrayBuffer: {
        CONTENTS_IMPL_POINTER_OFFSET: 0x10,
        SIZE_IN_BYTES_OFFSET_FROM_JSARRAYBUFFER_START: 0x30, // ATUALIZADO
        DATA_POINTER_OFFSET_FROM_JSARRAYBUFFER_START: 0x20,  // ATUALIZADO
    },
    ArrayBufferView: {
        STRUCTURE_ID_OFFSET: 0x00,
        FLAGS_OFFSET: 0x04,
        ASSOCIATED_ARRAYBUFFER_OFFSET: 0x08,
        M_VECTOR_OFFSET: 0x10,
        M_LENGTH_OFFSET: 0x18,
        M_MODE_OFFSET: 0x1C
    },
    JSFunction: { M_EXECUTABLE_OFFSET: "0x20", M_SCOPE_OFFSET: "0x28" },
    SymbolObject: { PRIVATE_SYMBOL_POINTER_OFFSET: 0x10 }
};

// !! PREENCHA ESTES COM VALORES HEXADECIMAIS REAIS DOS SEUS BINÁRIOS !!
export const KNOWN_STRUCTURE_IDS = {
    TYPE_ARRAY_BUFFER: "0xFILL_ME_IN_ARRAYBUFFER_ID",
    TYPE_UINT8_ARRAY:  "0xFILL_ME_IN_UINT8ARRAY_ID",
    TYPE_DATAVIEW:     "0xFILL_ME_IN_DATAVIEW_ID",
    TYPE_JS_FUNCTION:  "0xFILL_ME_IN_JSFUNCTION_ID",
    TYPE_JS_OBJECT_GENERIC: "0xFILL_ME_IN_JSOBJECT_ID",
    TYPE_JS_STRING:    "0xFILL_ME_IN_JSSTRING_ID",
    TYPE_JS_ARRAY:     "0xFILL_ME_IN_JSARRAY_ID",
    TYPE_FINAL_OBJECT: "0xFILL_ME_IN_FINALOBJECT_ID",
    TYPE_FAKE_TARGET_FOR_CONFUSION: "0xFILL_ME_IN_SOME_OTHER_ID",
};

export const WEBKIT_LIBRARY_INFO = { /* ... (mantenha o resto como estava) ... */ };
export let OOB_CONFIG = {ALLOCATION_SIZE: 32768, BASE_OFFSET_IN_DV: 128, INITIAL_BUFFER_SIZE: 32};
export function updateOOBConfigFromUI(docInstance) { /* ... (mantenha como estava) ... */ }
